spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mybetis_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


  redis:
    host:172.0.0.1
    port:6379
    password:root

mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port:  8081



